
== Your turn

Take a look to `PonyService.kt` try to implement `list()`

For this you must call `ponyRepository.findAll()` 
and use `mapper.map(MongoPony)` on each element of the list

All tests of `PonyServiceFindAllTest` must be ok.

== Review

[source, kotlin]
----
fun list(): List<Pony> {
    return ponyRepository.findAll()
            .map { mapper.map(it) }
}
----

[source, hideCode]
----
.
.
----

    
== Fun with more fun

[source, kotlin]
----
fun list(): List<Pony> {
    return ponyRepository.findAll()
            .map { mapper.map(it) }
}
----

[source, kotlin]
----
fun list(): List<Pony> = ponyRepository.findAll()
            .map { mapper.map(it) }
----

[NOTE.speaker]
--
When the body is simple we can use expression body
--


== Fun with more fun

[source, kotlin]
----
fun list(): List<Pony> {
    return ponyRepository.findAll()
            .map { mapper.map(it) }
}
----

[source, kotlin]
----
fun list() = ponyRepository.findAll()
            .map { mapper.map(it) }
----

[NOTE.speaker]
--
Type infered in expression body
--

== Expression

[source, kotlin]
----
var max: Int
if (a > b) {
    max = a
} else {
    max = b
}
----

== Expression

[source, kotlin]
----
var max =
if (a > b) {
    a
} else {
    b
}
----

== Expression

[source, kotlin]
----
var max = if (a > b) a else b



.
----
  
[NOTE.speaker]
--
Last expression is the value of a block:
Take if has example but works the same with while (see later?)
--

== Your turn

Take a look to `PonyService.kt` try to implement `save()`

If the id of the pony is null use `mapper.mapNew(pony)`
else use `ponyRepository.findById(ObjectId(pony.id))` and `mapper.update(fromDb, pony)`

and then call `ponyRepository.save(toSave)`

All tests of `PonyServiceSaveTest` must be ok.