== POJO to POKO

The first step into kotlin wil be to upgrate our POJO.
Let's take a look to the Pony class we will create the equivalent in kotlin

Right clic on Kotlin source folder -> `new Kotlin file/class`
Named it `bzh.zomzog.kotlinworkshop.domain.Pony` and it will be a `Class` 

In the java version we have four fileds, 
let's start with the id ;
[source, java]
----
    private final String id;
----

We use default getter/setter so we can use inferred one and remove `private`

Semicolon are optionnals so we can remove it. 

It's final so it's a `var`

It's a nullable String so it will be `id: String?`

So we have `val id: String` 

These properties must be initialized into the constructor so we have `class Pony(val id: String)`

Let's do the same for other properties 

// Trouver comment cacher du code spoiler alert

[source, kotlin]
----
class Pony(
    val id: String?,
    val name: String,
    val type: PonyType,
    val createdAt: LocalDateTime?
)
----

If we looks at Pony.java there is more than setters,
we have generated hashcode, equals and toString.

If you are familiar with `lombok` library it's a `@Data`.
This is native in kotlin, 
it's a `data class` this required at least one property and will do what we need.

So now we have 

[source, kotlin]
----
data class Pony(
    val id: String?,
    val name: String,
    val type: PonyType,
    val createdAt: LocalDateTime?
)
----

== PonyService

Let's have a look to `ponyService.java`

We will create Kotlin version.
Same as previous rigth clic on kotlin source foler ->  `new Kotlin file/class`
Named it `bzh.zomzog.kotlinworkshop.service.PonyService` and it will also be a `Class` 

Annotation will work in the same way :
[source, kotlin]
----
@Service
class PonyService {
}
----

We have two fields and constructor injection so this time they can be private.

[source, kotlin]
----
@Service
class PonyService(
  private val ponyRepository: PonyRepository, 
  private val mapper: PonyMapper) {
}
----

The easiest one is list current java is :

[source, java]
----
public List<Pony> list() {
    return ponyRepository.findAll()
            .stream()
            .map(mapper::map)
            .collect(Collectors.toList());
}
----

Function syntax in kotlin is `fun name(param:Type): returnType {}`

All is public by default so we can forget public modifier.

[source, kotlin]
----
fun list(): List<Pony> {


}
----

We still search on the repository

[source, kotlin]
----
fun list(): List<Pony> {
  return ponyRepository.findAll()

}
----

We still search on the repository

[source, kotlin]
----
fun list(): List<Pony> {
  return ponyRepository.findAll()

}
----

We don't need to transform it to a stram in kotlin

[source, kotlin]
----
fun list(): List<Pony> {
  return ponyRepository.findAll()
    .map(mapper::map)
}
----

Collector is not needed the result is already a list

=== ADVANCED TIPS

==== Lambda
When the last parameter of a function is a lambda,
you can put it into braces.

In our case it will be `.map { it -> mapper.map(it) }

By default lambda parameter is named `it` so it can be simplifed to `.map { mapper.map(it) }

==== Expression body

When the body is simple we can use expression body

[source, kotlin]
----
fun list(): List<Pony> = ponyRepository.findAll()
    .map(mapper::map)
----

With expression body type is infered we can again simplify it with

[source, kotlin]
----
fun list() = ponyRepository.findAll()
    .map(mapper::map)
----


=== Save

[source, java]
----
public Pony save(Pony pony) {
    PonyMongo updated;
    if (null == pony.getId()) {
        updated = ponyRepository.save(mapper.map(pony));
    } else {
        final Optional<PonyMongo> fromDb = ponyRepository.findById(new ObjectId(pony.getId()));
        updated = fromDb.map(it -> mapper.update(it, pony))
                .orElseThrow(() -> new RuntimeException("Pony not found")); // TODO Named exception
    }
    return mapper.map(updated);
}
----

Let's start with fun 
[source, kotlin]
----
fun save(pony: Pony): Pony {

}
----

In Kotlin, if can also be used as an expression:
[source, kotlin]
----
fun save(pony: Pony): Pony {
  val updated = if (null == pony.id) {
  
  } else {

  }
  return mapper.map(updated)
}
----
